### ISSUE TITLE
support for days beginning/ending at times other than midnight

### ISSUE THREAD

**Issue by kenirwin** [cazzerson/Suma#32]
Hi folks,

I'd love to add a configuration/feature that would support nightly reports that handle early morning hours as part of "last night". 

I'm imagining a variable in analysis/config/config_example.yaml that might look something like:
nightly: 
 day_begins: 4am

That would tell the nightly reporting function to treat all of activity between midnight and 4am as "last night" for reporting purposes, so the reporting period would go from 4am yesterday to 3:59 today. 

I'd be glad to work with you all on developing something like this. We'd find it very handy during the times when our library is open after midnight (only a few times a year).

Thanks
Ken

**Comment by bretdavidson** [comment]
Hi Ken,

This seems like an interesting idea to us and is something we would like to try to implement.

Here is a short list of other items to consider:

1. I'm thinking that the setting could be promoted to the filter interface rather than a config so that end-users of the analysis tools have control over this setting for queries. 

2. The analysis tools should also provide strong visual feedback to users that something other than "midnight" is being used to define a 24-hour period. 

3. The data processing code should be modified in a way that it continues to support both the time series report and the hourly report. The hourly report should rely on the default setting.

4. We will need to think about how to retrieve extra days in order to complete the 24-hour period at the end of a date range.

5. I think this setting should probably be limited to choosing the start time for a 24-hour period in hour increments.

6. This feature seems to boil down to changing the date of hours that overlap into the next calendar day, which can be handled in the method that selects which date to use for an individual count. Currently, it evaluates the session start time, session end time, or count time, but could be expanded to support this. 

7. One possible difficulty is the issue of communicating the order of hours. For instance, using your 4AM example, the hours from 12-3:59 that are pulled in from the next day will need to be displayed in a way that the user knows they occurred AFTER the 4 AM with the adjusted date. I don't think this is an issue with the time series itself, but will be for the tabular and export data.

Let me know if you see any other difficulties I've missed or if you have other thoughts and ideas about this feature. I'll try to take a first pass at this in the next couple of weeks. 

Thanks,

Bret

**Comment by kenirwin** [comment]
I hadn't thought about the web-based reports, but I guess that including the option there makes some sense -- I was only focused on the nightly reports, which I think would be a little less complex and that's where I think the config idea makes sense. I do think that the how-to-make-the-information-clear aspect becomes trickier. Here's a quick stab at how we might lay out the hour report heat map: (the line chart works fine as-is)
![suma-madrugada](https://cloud.githubusercontent.com/assets/1894561/6627597/98fd85f0-c8d5-11e4-8f7c-41297a61ab9e.png)

I'm not familiar with how this all works on the data processing side, so I'm not sure what adjustments you'd have to make in order to make that work in the reports.

Am I right in thinking that the code the generates the nightly reports is entirely separate from the code that generates the web-based reports? Or is there something that's in play for both of them? 

Thanks
Ken

**Comment by bretdavidson** [comment]
Yes, the code that generates the nightly report is separate from the web report code, but I think they should be merged. I agree that the nightly report could be handled with a configuration option, or maybe as an argument to the execution of the script. I'm working on this currently and will try to get some initial code up for review soon. 

Thanks for reviewing this!

Bret

**Comment by bretdavidson** [comment]
Hi Ken,

I've pushed a branch [startHour](https://github.com/cazzerson/Suma/tree/startHour) that now supports arbitrary definition of a 24-hour day both in the analysis tools and in the nightly report. To use in the nightly report, just pass an additional argument to the script like --start-hour=0400. Let me know what you think.

Bret

**Comment by bretdavidson** [comment]
Hi Ken,

I've gone ahead and merged this branch into master. If you see any issues, please open another ticket here or feel free to contact me via e-mail.

Thanks!

Bret
